name: Clean up build env
on:
  workflow_dispatch:
  
jobs:
  build_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup unused directories and tools
        run: |
          df -h /
          sudo apt-get remove -y '^aspnetcore-.*' '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-chrome-stable firefox powershell mono-devel google-cloud-sdk google-cloud-cli microsoft-edge-stable snapd --fix-missing 
          sudo apt-get autoremove -y 
          sudo apt-get clean
          sudo docker image prune --all --force
          sudo rm -rf \
            "$AGENT_TOOLSDIRECTORY" \
            /opt/google/chrome \
            /opt/microsoft/msedge \
            /opt/microsoft/powershell \
            /opt/pipx \
            /usr/lib/mono \
            /usr/local/julia* \
            /usr/local/lib/android \
            /usr/local/lib/node_modules \
            /usr/local/share/chromium \
            /usr/local/share/powershell \
            /usr/share/dotnet \
            /usr/share/swift \ 
            /usr/local/share/boost \
            /opt/hostedtoolcache/ \
            /usr/local/graalvm/   
          ghcup nuke
          df -h /
